name: CI-TOKEN
on:   
  push:

jobs:
  armv7_job:
    runs-on: ubuntu-24.04
    name: Build on ubuntu-22.04 armv7
    steps:
      - uses: actions/checkout@v4
      - uses: uraimo/run-on-arch-action@v3
        name: Run commands
        id: runcmd
        with:
          arch: armv7
          distro: ubuntu24.04
          run: |
            uname -m
