name: CI-TOKEN
on:   
  push:

jobs:
  armv7_job:
    runs-on: ubuntu-24.04
    name: Build on ubuntu-22.04 armv7
    steps:
    - uses: actions/checkout@v2
    - uses: pguyot/arm-runner-action@v2
      with:
        commands: |
            uname -m
